/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : smpu1.c
**     Project     : Driving_Assistance_System_NXP_Z2_2
**     Processor   : MPC5748G_324
**     Component   : smpu
**     Version     : Component SDK_S32_PA_11, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_11
**     Compiler    : GNU C Compiler
**     Date/Time   : 2024-06-24, 15:18, # CodeGen: 12
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file smpu1.c
** @version 01.00
*/         
/*!
**  @addtogroup smpu1_module smpu1 module documentation
**  @{
*/         

/* MODULE smpu1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variable will be used in other source file that user initialize
 * to use this module.
 */

#include "smpu1.h"
#include "stddef.h"

/*! Master access rights configuration 0 */
const smpu_master_access_right_t smpu1_AccessRightConfig0[] =
{
    /*! CORE_Z4A */
    {
        .masterNum = FEATURE_SMPU_MASTER_CORE_Z4A,              /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! CORE_Z4B */
    {
        .masterNum = FEATURE_SMPU_MASTER_CORE_Z4B,              /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! CORE_Z2 */
    {
        .masterNum = FEATURE_SMPU_MASTER_CORE_Z2,               /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! DEBUG_Z4A */
    {
        .masterNum = FEATURE_SMPU_MASTER_DEBUG_Z4A,             /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! DEBUG_Z4B */
    {
        .masterNum = FEATURE_SMPU_MASTER_DEBUG_Z4B,             /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! DEBUG_Z2 */
    {
        .masterNum = FEATURE_SMPU_MASTER_DEBUG_Z2,              /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! EDMA */
    {
        .masterNum = FEATURE_SMPU_MASTER_EDMA,                  /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! ENET0 */
    {
        .masterNum = FEATURE_SMPU_MASTER_ENET0,                 /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! ENET1 */
    {
        .masterNum = FEATURE_SMPU_MASTER_ENET1,                 /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! FLEXRAY */
    {
        .masterNum = FEATURE_SMPU_MASTER_FLEXRAY,               /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! HSM */
    {
        .masterNum = FEATURE_SMPU_MASTER_HSM,                   /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! MLB */
    {
        .masterNum = FEATURE_SMPU_MASTER_MLB,                   /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! USB0 */
    {
        .masterNum = FEATURE_SMPU_MASTER_USB0,                  /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! USB1 */
    {
        .masterNum = FEATURE_SMPU_MASTER_USB1,                  /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    },
    /*! USDHC */
    {
        .masterNum = FEATURE_SMPU_MASTER_USDHC,                 /*!< Master number */
        .accessRight = SMPU_RW_OR_SET_3,                        /*!< Access right */
    }
};

/*! User configuration 0 */
const smpu_user_config_t smpu1_UserConfig0[] =
{
    /*! Region number 0
        Name: Region 0 */
    {
        .startAddr           = 0x00000000U,                     /*!< Memory region start address */
        .endAddr             = 0xFFFFFFFFU,                     /*!< Memory region end address */
        .specAccessEnable    = false,                           /*!< Specific access enable */
        .specAccessSet       = NULL,                            /*!< Specific access configurations */
        .masterAccRight      = smpu1_AccessRightConfig0,        /*!< Master access right */
        .cacheInhibitEnable  = false,                           /*!< Cache inhibit enable */
        .processIdEnable     = false,                           /*!< Process identifier enable */
        .processIdentifier   = 0x00U,                           /*!< Process identifier */
        .processIdMask       = 0x00U,                           /*!< Process identifier mask */
        .lockConfig          = SMPU_UNLOCK                      /*!< Lock configuration */
    }
};
/* END smpu1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
